// <auto-generated />
using System;
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.Catacion
{
    [DbContext(typeof(CatacionContext))]
    [Migration("20250617172919_InitialCreate_CatacionContext")]
    partial class InitialCreate_CatacionContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.CatacionItem", b =>
                {
                    b.Property<int>("ID_catacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_catacion"));

                    b.Property<decimal>("C1ME")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C1agrio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C1cerezaseca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C1hongos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C1insectos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C1negro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C2agrioP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C2averanado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C2cascara_pulpa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C2concha")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C2flotador")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("C2inmaduro")
                        .HasColumnType("integer");

                    b.Property<decimal>("C2insectos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C2negroP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("C2partido_cortado_mordido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("C2pergamino")
                        .HasColumnType("integer");

                    b.Property<int>("CCcalidad")
                        .HasColumnType("integer");

                    b.Property<string>("CCcverde")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Catorce")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Defectuoso")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Diecinueve")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Dieciocho")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Dieciseis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Diecisiete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Dtueste")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FFreposo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Limpio")
                        .HasColumnType("boolean");

                    b.Property<string>("Nlote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Overde")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Pfinales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quaker")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quince")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Residuo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rtostado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TAgtron")
                        .HasColumnType("integer");

                    b.Property<decimal>("Trece")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TresSobreDieciseis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Veinte")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_catacion");

                    b.ToTable("Catacion");
                });
#pragma warning restore 612, 618
        }
    }
}
