// <auto-generated />
using System;
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.Bodega
{
    [DbContext(typeof(BodegaContext))]
    [Migration("20250617172900_InitialCreate_BodegaContext")]
    partial class InitialCreate_BodegaContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.BodegaItem", b =>
                {
                    b.Property<int>("ID_Bodega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Bodega"));

                    b.Property<int>("CantidadSacos")
                        .HasColumnType("integer");

                    b.Property<decimal>("D_Bellota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("D_Pergamino")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FinicioReposo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Hfinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hinicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nlote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PMH_relativa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PMTexterna")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PMTinterna")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("W_bellota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("W_pergamino")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Bodega");

                    b.ToTable("Bodega");
                });
#pragma warning restore 612, 618
        }
    }
}
