// <auto-generated />
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.Registro_Formulario
{
    [DbContext(typeof(Registro_FormularioContext))]
    partial class Registro_FormularioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.Registro_FormularioItem", b =>
                {
                    b.Property<int>("ID_Formulario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Formulario"));

                    b.Property<int>("ID_inmaduras")
                        .HasColumnType("integer");

                    b.Property<int>("ID_maduras")
                        .HasColumnType("integer");

                    b.Property<int>("ID_sobremaduras")
                        .HasColumnType("integer");

                    b.HasKey("ID_Formulario");

                    b.ToTable("Registro_Formulario");
                });
#pragma warning restore 612, 618
        }
    }
}
