// <auto-generated />
using System;
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.Secado
{
    [DbContext(typeof(SecadoContext))]
    [Migration("20250617173426_InitialCreate_SecadoContext")]
    partial class InitialCreate_SecadoContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.SecadoItem", b =>
                {
                    b.Property<int>("ID_Secado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Secado"));

                    b.Property<decimal>("Dsecado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Ffinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Finicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nlote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Pmecanico")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Psolar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Secado");

                    b.ToTable("Secado");
                });
#pragma warning restore 612, 618
        }
    }
}
