// <auto-generated />
using System;
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.RCinmaduras
{
    [DbContext(typeof(RCinmadurasContext))]
    partial class RCinmadurasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.RCinmadurasItem", b =>
                {
                    b.Property<int>("ID_inmaduras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_inmaduras"));

                    b.Property<decimal>("Gbx")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Promedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Tiempo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID_inmaduras");

                    b.ToTable("RCinmaduras");
                });
#pragma warning restore 612, 618
        }
    }
}
