// <auto-generated />
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.Enviar_muestras
{
    [DbContext(typeof(Enviar_muestrasContext))]
    [Migration("20250818011458_InitialCreate_EnviarMuestras")]
    partial class InitialCreate_EnviarMuestras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.Enviar_muestrasItem", b =>
                {
                    b.Property<int>("ID_Trilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Trilla"));

                    b.Property<int>("ID_Catacion")
                        .HasColumnType("integer");

                    b.HasKey("ID_Trilla");

                    b.ToTable("Enviar_muestras");
                });
#pragma warning restore 612, 618
        }
    }
}
