// <auto-generated />
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.Gbx_sobremaduras
{
    [DbContext(typeof(Gbx_sobremadurasContext))]
    [Migration("20250818011526_InitialCreate_GbxSobremaduras")]
    partial class InitialCreate_GbxSobremaduras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.Gbx_sobremadurasItem", b =>
                {
                    b.Property<int>("ID_Gbx_sobremaduras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Gbx_sobremaduras"));

                    b.Property<int>("ID_sobremaduras")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Gbx_sobremaduras");

                    b.ToTable("Gbx_sobremaduras");
                });
#pragma warning restore 612, 618
        }
    }
}
