// <auto-generated />
using System;
using CoffeeBeanFlowAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeBeanFlowAPI.Migrations
{
    [DbContext(typeof(CoffeeBeanFlowDbContext))]
    [Migration("20251214065451_AddRelacionesNN")]
    partial class AddRelacionesNN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.CaracterizacionEntity", b =>
                {
                    b.Property<DateTime>("Tiempo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tiempo");

                    b.Property<decimal?>("Broca")
                        .HasColumnType("numeric")
                        .HasColumnName("broca");

                    b.Property<int?>("Cinmaduras")
                        .HasColumnType("integer")
                        .HasColumnName("c_inmaduras");

                    b.Property<int?>("Cobjetivo")
                        .HasColumnType("integer")
                        .HasColumnName("c_objetivo");

                    b.Property<int?>("Csecas")
                        .HasColumnType("integer")
                        .HasColumnName("c_secas");

                    b.Property<int?>("Csobremaduras")
                        .HasColumnType("integer")
                        .HasColumnName("c_sobremaduras");

                    b.Property<int?>("Cverdes")
                        .HasColumnType("integer")
                        .HasColumnName("c_verdes");

                    b.Property<decimal?>("DRmaduras")
                        .HasColumnType("numeric")
                        .HasColumnName("dr_maduras");

                    b.Property<decimal?>("Densidad")
                        .HasColumnType("numeric")
                        .HasColumnName("densidad");

                    b.Property<decimal?>("Emaduracion")
                        .HasColumnType("numeric")
                        .HasColumnName("e_maduracion");

                    b.Property<string>("LAsignado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("l_asignado");

                    b.Property<decimal?>("Mtabla")
                        .HasColumnType("numeric")
                        .HasColumnName("m_tabla");

                    b.Property<string>("NloteAreaAcopio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nlote_area_acopio");

                    b.Property<decimal?>("PCdebajo")
                        .HasColumnType("numeric")
                        .HasColumnName("pc_debajo");

                    b.Property<decimal?>("PCencima")
                        .HasColumnType("numeric")
                        .HasColumnName("pc_encima");

                    b.Property<decimal?>("PCobjetivo")
                        .HasColumnType("numeric")
                        .HasColumnName("pc_objetivo");

                    b.Property<decimal?>("PCsecas")
                        .HasColumnType("numeric")
                        .HasColumnName("pc_secas");

                    b.Property<decimal?>("PCverdes")
                        .HasColumnType("numeric")
                        .HasColumnName("pc_verdes");

                    b.Property<string>("Proceso")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proceso");

                    b.Property<int?>("Secos")
                        .HasColumnType("integer")
                        .HasColumnName("secos");

                    b.Property<int?>("Vanos")
                        .HasColumnType("integer")
                        .HasColumnName("vanos");

                    b.HasKey("Tiempo");

                    b.HasIndex("NloteAreaAcopio");

                    b.ToTable("formulario_caracterizacion");
                });

            modelBuilder.Entity("Backend.Models.CatacionEntity", b =>
                {
                    b.Property<int>("IdCatacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_catacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCatacion"));

                    b.Property<decimal?>("C1ME")
                        .HasColumnType("numeric")
                        .HasColumnName("c1me");

                    b.Property<decimal?>("C1agrio")
                        .HasColumnType("numeric")
                        .HasColumnName("c1agrio");

                    b.Property<decimal?>("C1agrioP")
                        .HasColumnType("numeric")
                        .HasColumnName("c1agriop");

                    b.Property<decimal?>("C1cerezaseca")
                        .HasColumnType("numeric")
                        .HasColumnName("c1cerezaseca");

                    b.Property<decimal?>("C1hongos")
                        .HasColumnType("numeric")
                        .HasColumnName("c1hongos");

                    b.Property<decimal?>("C1insectos")
                        .HasColumnType("numeric")
                        .HasColumnName("c1insectos");

                    b.Property<decimal?>("C1negro")
                        .HasColumnType("numeric")
                        .HasColumnName("c1negro");

                    b.Property<decimal?>("C1negroP")
                        .HasColumnType("numeric")
                        .HasColumnName("c1negrop");

                    b.Property<decimal?>("C2averanado")
                        .HasColumnType("numeric")
                        .HasColumnName("c2averanado");

                    b.Property<decimal?>("C2cascara")
                        .HasColumnType("numeric")
                        .HasColumnName("c2cascara");

                    b.Property<decimal?>("C2concha")
                        .HasColumnType("numeric")
                        .HasColumnName("c2concha");

                    b.Property<decimal?>("C2cortado")
                        .HasColumnType("numeric")
                        .HasColumnName("c2cortado");

                    b.Property<decimal?>("C2flotador")
                        .HasColumnType("numeric")
                        .HasColumnName("c2flotador");

                    b.Property<decimal?>("C2inmaduro")
                        .HasColumnType("numeric")
                        .HasColumnName("c2inmaduro");

                    b.Property<decimal?>("C2insectos")
                        .HasColumnType("numeric")
                        .HasColumnName("c2insectos");

                    b.Property<decimal?>("C2mordido")
                        .HasColumnType("numeric")
                        .HasColumnName("c2mordido");

                    b.Property<decimal?>("C2partido")
                        .HasColumnType("numeric")
                        .HasColumnName("c2partido");

                    b.Property<decimal?>("C2pergamino")
                        .HasColumnType("numeric")
                        .HasColumnName("c2pergamino");

                    b.Property<decimal?>("C2pulpa")
                        .HasColumnType("numeric")
                        .HasColumnName("c2pulpa");

                    b.Property<decimal?>("CCcalidad")
                        .HasColumnType("numeric")
                        .HasColumnName("cccalidad");

                    b.Property<decimal?>("CCverde")
                        .HasColumnType("numeric")
                        .HasColumnName("ccverde");

                    b.Property<decimal?>("Catorce")
                        .HasColumnType("numeric")
                        .HasColumnName("catorce");

                    b.Property<decimal?>("Defectuoso")
                        .HasColumnType("numeric")
                        .HasColumnName("defectuoso");

                    b.Property<decimal?>("Dfueste")
                        .HasColumnType("numeric")
                        .HasColumnName("dfueste");

                    b.Property<decimal?>("Diecinueve")
                        .HasColumnType("numeric")
                        .HasColumnName("diecinueve");

                    b.Property<decimal?>("Dieciocho")
                        .HasColumnType("numeric")
                        .HasColumnName("dieciocho");

                    b.Property<decimal?>("Dieciseis")
                        .HasColumnType("numeric")
                        .HasColumnName("dieciseis");

                    b.Property<decimal?>("Diecisiete")
                        .HasColumnType("numeric")
                        .HasColumnName("diecisiete");

                    b.Property<decimal?>("FFreposo")
                        .HasColumnType("numeric")
                        .HasColumnName("ffreposo");

                    b.Property<decimal?>("Limpio")
                        .HasColumnType("numeric")
                        .HasColumnName("limpio");

                    b.Property<string>("Nlote")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nlote");

                    b.Property<decimal?>("Overde")
                        .HasColumnType("numeric")
                        .HasColumnName("overde");

                    b.Property<decimal?>("Pfinales")
                        .HasColumnType("numeric")
                        .HasColumnName("pfinales");

                    b.Property<decimal?>("Quaker")
                        .HasColumnType("numeric")
                        .HasColumnName("quaker");

                    b.Property<decimal?>("Quince")
                        .HasColumnType("numeric")
                        .HasColumnName("quince");

                    b.Property<decimal?>("Rtostado")
                        .HasColumnType("numeric")
                        .HasColumnName("rtostado");

                    b.Property<decimal?>("Tonagton25")
                        .HasColumnType("numeric")
                        .HasColumnName("tonagton_25");

                    b.Property<decimal?>("Tonagton35")
                        .HasColumnType("numeric")
                        .HasColumnName("tonagton_35");

                    b.Property<decimal?>("Tonagton45")
                        .HasColumnType("numeric")
                        .HasColumnName("tonagton_45");

                    b.Property<decimal?>("Tonagton55")
                        .HasColumnType("numeric")
                        .HasColumnName("tonagton_55");

                    b.Property<decimal?>("Tonagton65")
                        .HasColumnType("numeric")
                        .HasColumnName("tonagton_65");

                    b.Property<decimal?>("Tonagton75")
                        .HasColumnType("numeric")
                        .HasColumnName("tonagton_75");

                    b.Property<decimal?>("Tonagton85")
                        .HasColumnType("numeric")
                        .HasColumnName("tonagton_85");

                    b.Property<decimal?>("Tonagton95")
                        .HasColumnType("numeric")
                        .HasColumnName("tonagton_95");

                    b.Property<decimal?>("Trece")
                        .HasColumnType("numeric")
                        .HasColumnName("trece");

                    b.Property<decimal?>("TresSobreDieciseis")
                        .HasColumnType("numeric")
                        .HasColumnName("tres_sobre_dieciseis");

                    b.Property<decimal?>("Veinte")
                        .HasColumnType("numeric")
                        .HasColumnName("veinte");

                    b.HasKey("IdCatacion");

                    b.ToTable("catacion");
                });

            modelBuilder.Entity("Backend.Models.EnviarMuestrasEntity", b =>
                {
                    b.Property<int>("IdTrilla")
                        .HasColumnType("integer")
                        .HasColumnName("id_trilla");

                    b.Property<int>("IdCatacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_catacion");

                    b.Property<decimal?>("FfinalReposo")
                        .HasColumnType("numeric")
                        .HasColumnName("ffinal_reposo");

                    b.HasKey("IdTrilla", "IdCatacion");

                    b.HasIndex("IdCatacion");

                    b.ToTable("enviar_muestras");
                });

            modelBuilder.Entity("Backend.Models.RCinmadurasEntity", b =>
                {
                    b.Property<int>("IdInmaduras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_inmaduras");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInmaduras"));

                    b.Property<decimal?>("Gbx")
                        .HasColumnType("numeric")
                        .HasColumnName("gbx");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("Promedio")
                        .HasColumnType("numeric")
                        .HasColumnName("promedio");

                    b.Property<DateTime>("Tiempo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tiempo");

                    b.HasKey("IdInmaduras");

                    b.HasIndex("Tiempo")
                        .IsUnique();

                    b.ToTable("rc_inmaduras");
                });

            modelBuilder.Entity("Backend.Models.RCmadurasEntity", b =>
                {
                    b.Property<int>("IdMaduras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_maduras");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMaduras"));

                    b.Property<decimal?>("Gbx")
                        .HasColumnType("numeric")
                        .HasColumnName("gbx");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("Promedio")
                        .HasColumnType("numeric")
                        .HasColumnName("promedio");

                    b.Property<DateTime>("Tiempo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tiempo");

                    b.HasKey("IdMaduras");

                    b.HasIndex("Tiempo")
                        .IsUnique();

                    b.ToTable("rc_maduras");
                });

            modelBuilder.Entity("Backend.Models.RCsobremadurasEntity", b =>
                {
                    b.Property<int>("IdSobremaduras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_sobremaduras");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSobremaduras"));

                    b.Property<decimal?>("Gbx")
                        .HasColumnType("numeric")
                        .HasColumnName("gbx");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("Promedio")
                        .HasColumnType("numeric")
                        .HasColumnName("promedio");

                    b.Property<DateTime>("Tiempo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tiempo");

                    b.HasKey("IdSobremaduras");

                    b.HasIndex("Tiempo")
                        .IsUnique();

                    b.ToTable("rc_sobremaduras");
                });

            modelBuilder.Entity("Backend.Models.RondasEntity", b =>
                {
                    b.Property<int>("IdRondas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rondas");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRondas"));

                    b.Property<int>("IdCatacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_catacion");

                    b.Property<decimal?>("ValorCalidad")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_calidad");

                    b.HasKey("IdRondas");

                    b.HasIndex("IdCatacion");

                    b.ToTable("rondas");
                });

            modelBuilder.Entity("Backend.Models.SuministraEntity", b =>
                {
                    b.Property<int>("IdBodega")
                        .HasColumnType("integer")
                        .HasColumnName("id_bodega");

                    b.Property<int>("IdTrilla")
                        .HasColumnType("integer")
                        .HasColumnName("id_trilla");

                    b.HasKey("IdBodega", "IdTrilla");

                    b.HasIndex("IdTrilla");

                    b.ToTable("suministra");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.AreaAcopioEntity", b =>
                {
                    b.Property<string>("Nlote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nlote");

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric")
                        .HasColumnName("altura");

                    b.Property<bool?>("Anaerobico")
                        .HasColumnType("boolean")
                        .HasColumnName("anaerobico");

                    b.Property<decimal?>("Disponible")
                        .HasColumnType("numeric")
                        .HasColumnName("disponible");

                    b.Property<string>("Enproceso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("enproceso");

                    b.Property<bool?>("Lavado")
                        .HasColumnType("boolean")
                        .HasColumnName("lavado");

                    b.Property<bool?>("Miel")
                        .HasColumnType("boolean")
                        .HasColumnName("miel");

                    b.Property<bool?>("Natural")
                        .HasColumnType("boolean")
                        .HasColumnName("natural");

                    b.Property<string>("Nfinca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nfinca");

                    b.Property<string>("Nproductor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nproductor");

                    b.Property<int>("Nrecibo")
                        .HasColumnType("integer")
                        .HasColumnName("nrecibo");

                    b.Property<string>("Otro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("otro");

                    b.Property<decimal?>("PDensidad_Fruta")
                        .HasColumnType("numeric")
                        .HasColumnName("pdensidad_fruta");

                    b.Property<decimal?>("PDensidad_Pergamino_Humedo")
                        .HasColumnType("numeric")
                        .HasColumnName("pdensidad_pergamino_humedo");

                    b.Property<decimal?>("PF_DMecanicos")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_dmecanicos");

                    b.Property<decimal?>("PF_Pergamino_Pulpa")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_pergamino_pulpa");

                    b.Property<decimal?>("PF_Pulpa_Pergamino")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_pulpa_pergamino");

                    b.Property<decimal?>("PF_Segundas")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_segundas");

                    b.Property<decimal?>("Robjetivo")
                        .HasColumnType("numeric")
                        .HasColumnName("robjetivo");

                    b.Property<decimal?>("Rtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("rtotal");

                    b.Property<bool?>("Semilavado")
                        .HasColumnType("boolean")
                        .HasColumnName("semilavado");

                    b.Property<bool>("Vendido")
                        .HasColumnType("boolean")
                        .HasColumnName("vendido");

                    b.Property<string>("Zona")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zona");

                    b.HasKey("Nlote");

                    b.ToTable("area_acopio");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.BodegaEntity", b =>
                {
                    b.Property<int>("IdBodega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_bodega");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBodega"));

                    b.Property<int?>("CantidadSacos")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_sacos");

                    b.Property<decimal?>("DBellota")
                        .HasColumnType("numeric")
                        .HasColumnName("d_bellota");

                    b.Property<decimal?>("DPergamino")
                        .HasColumnType("numeric")
                        .HasColumnName("d_pergamino");

                    b.Property<DateTime?>("FinicioReposo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finicio_reposo");

                    b.Property<decimal?>("Hfinal")
                        .HasColumnType("numeric")
                        .HasColumnName("hfinal");

                    b.Property<decimal?>("Hinicial")
                        .HasColumnType("numeric")
                        .HasColumnName("hinicial");

                    b.Property<string>("Nlote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nlote");

                    b.Property<decimal?>("PMHRelativa")
                        .HasColumnType("numeric")
                        .HasColumnName("pmh_relativa");

                    b.Property<decimal?>("PMTExterna")
                        .HasColumnType("numeric")
                        .HasColumnName("pmt_externa");

                    b.Property<decimal?>("PMTInterna")
                        .HasColumnType("numeric")
                        .HasColumnName("pmt_interna");

                    b.Property<decimal?>("WBellota")
                        .HasColumnType("numeric")
                        .HasColumnName("w_bellota");

                    b.Property<decimal?>("WPergamino")
                        .HasColumnType("numeric")
                        .HasColumnName("w_pergamino");

                    b.HasKey("IdBodega");

                    b.HasIndex("Nlote");

                    b.ToTable("bodega");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.GuardarCafeEntity", b =>
                {
                    b.Property<int>("IdSecado")
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    b.Property<int>("IdBodega")
                        .HasColumnType("integer")
                        .HasColumnName("id_bodega");

                    b.Property<int>("CantidadSacos")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_sacos");

                    b.HasKey("IdSecado", "IdBodega");

                    b.HasIndex("IdBodega");

                    b.ToTable("guardar_cafe");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.HumedadEntity", b =>
                {
                    b.Property<int>("IdHumedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_humedad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHumedad"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Humedad")
                        .HasColumnType("numeric")
                        .HasColumnName("humedad");

                    b.Property<int>("IdSecado")
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    b.HasKey("IdHumedad");

                    b.HasIndex("IdSecado");

                    b.ToTable("humedad");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.NcamaEntity", b =>
                {
                    b.Property<int>("IdNcama")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ncama");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNcama"));

                    b.Property<int>("IdSecado")
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    b.Property<string>("NumeroCama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_cama");

                    b.HasKey("IdNcama");

                    b.HasIndex("IdSecado");

                    b.ToTable("ncama");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.PesoVerdeEntity", b =>
                {
                    b.Property<int>("IdPesoVerde")
                        .HasColumnType("integer")
                        .HasColumnName("id_peso_verde");

                    b.Property<decimal?>("WFinalInferiores")
                        .HasColumnType("numeric")
                        .HasColumnName("wfinal_inferiores");

                    b.Property<decimal?>("Wfinal")
                        .HasColumnType("numeric")
                        .HasColumnName("wfinal");

                    b.Property<decimal?>("Winferiores")
                        .HasColumnType("numeric")
                        .HasColumnName("winferiores");

                    b.HasKey("IdPesoVerde");

                    b.ToTable("peso_verde");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.SecadoEntity", b =>
                {
                    b.Property<int>("IdSecado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSecado"));

                    b.Property<int?>("Dsecado")
                        .HasColumnType("integer")
                        .HasColumnName("dsecado");

                    b.Property<DateTime?>("Ffinal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ffinal");

                    b.Property<DateTime>("Finicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finicio");

                    b.Property<string>("Nlote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nlote");

                    b.HasKey("IdSecado");

                    b.HasIndex("Nlote");

                    b.ToTable("secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.TemperaturaSecadoEntity", b =>
                {
                    b.Property<int>("IdTemperaturaSecado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_temperatura_secado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTemperaturaSecado"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdSecado")
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("numeric")
                        .HasColumnName("temperatura");

                    b.HasKey("IdTemperaturaSecado");

                    b.HasIndex("IdSecado");

                    b.ToTable("temperatura_secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.TermoHigrometriaEntity", b =>
                {
                    b.Property<int>("IdTermoHigrometria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_termo_higrometria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTermoHigrometria"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("HumedadAmbiente")
                        .HasColumnType("numeric")
                        .HasColumnName("humedad_ambiente");

                    b.Property<int>("IdSecado")
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    b.Property<decimal>("TemperaturaAmbiente")
                        .HasColumnType("numeric")
                        .HasColumnName("temperatura_ambiente");

                    b.HasKey("IdTermoHigrometria");

                    b.HasIndex("IdSecado");

                    b.ToTable("termo_higrometria");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.TrillaEntity", b =>
                {
                    b.Property<int>("IdTrilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_trilla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTrilla"));

                    b.Property<DateTime?>("FfinalReposo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ffinal_reposo");

                    b.Property<decimal?>("Hfinal")
                        .HasColumnType("numeric")
                        .HasColumnName("hfinal");

                    b.Property<decimal?>("Hinicial")
                        .HasColumnType("numeric")
                        .HasColumnName("hinicial");

                    b.Property<string>("Nlote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nlote");

                    b.Property<decimal?>("Pbarreduras")
                        .HasColumnType("numeric")
                        .HasColumnName("pbarreduras");

                    b.Property<decimal?>("Pcaracolillo")
                        .HasColumnType("numeric")
                        .HasColumnName("pcaracolillo");

                    b.Property<decimal?>("Pcataduras")
                        .HasColumnType("numeric")
                        .HasColumnName("pcataduras");

                    b.Property<decimal?>("Pescogeduras")
                        .HasColumnType("numeric")
                        .HasColumnName("pescogeduras");

                    b.Property<decimal?>("Pinferiores")
                        .HasColumnType("numeric")
                        .HasColumnName("pinferiores");

                    b.Property<decimal?>("Pmadres")
                        .HasColumnType("numeric")
                        .HasColumnName("pmadres");

                    b.Property<decimal?>("Pmenudos")
                        .HasColumnType("numeric")
                        .HasColumnName("pmenudos");

                    b.Property<decimal?>("Pprimera")
                        .HasColumnType("numeric")
                        .HasColumnName("pprimera");

                    b.Property<decimal?>("Psegundas")
                        .HasColumnType("numeric")
                        .HasColumnName("psegundas");

                    b.Property<decimal?>("RFinalPelado")
                        .HasColumnType("numeric")
                        .HasColumnName("rfinal_pelado");

                    b.Property<decimal?>("RFinalSeleccion")
                        .HasColumnType("numeric")
                        .HasColumnName("rfinal_seleccion");

                    b.Property<decimal?>("RTeoricoSeleccion")
                        .HasColumnType("numeric")
                        .HasColumnName("rteorico_seleccion");

                    b.Property<decimal?>("RteoricoPelado")
                        .HasColumnType("numeric")
                        .HasColumnName("rteorico_pelado");

                    b.Property<decimal?>("WverdeFinal")
                        .HasColumnType("numeric")
                        .HasColumnName("wverde_final");

                    b.Property<decimal?>("WverdeTeorico")
                        .HasColumnType("numeric")
                        .HasColumnName("wverde_teorico");

                    b.HasKey("IdTrilla");

                    b.HasIndex("Nlote");

                    b.ToTable("trilla");
                });

            modelBuilder.Entity("Backend.Models.CaracterizacionEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.AreaAcopioEntity", "AreaAcopio")
                        .WithMany()
                        .HasForeignKey("NloteAreaAcopio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaAcopio");
                });

            modelBuilder.Entity("Backend.Models.EnviarMuestrasEntity", b =>
                {
                    b.HasOne("Backend.Models.CatacionEntity", "Catacion")
                        .WithMany()
                        .HasForeignKey("IdCatacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeBeanFlowAPI.Models.TrillaEntity", "Trilla")
                        .WithMany()
                        .HasForeignKey("IdTrilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catacion");

                    b.Navigation("Trilla");
                });

            modelBuilder.Entity("Backend.Models.RCinmadurasEntity", b =>
                {
                    b.HasOne("Backend.Models.CaracterizacionEntity", "Caracterizacion")
                        .WithOne("RCinmaduras")
                        .HasForeignKey("Backend.Models.RCinmadurasEntity", "Tiempo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracterizacion");
                });

            modelBuilder.Entity("Backend.Models.RCmadurasEntity", b =>
                {
                    b.HasOne("Backend.Models.CaracterizacionEntity", "Caracterizacion")
                        .WithOne("RCmaduras")
                        .HasForeignKey("Backend.Models.RCmadurasEntity", "Tiempo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracterizacion");
                });

            modelBuilder.Entity("Backend.Models.RCsobremadurasEntity", b =>
                {
                    b.HasOne("Backend.Models.CaracterizacionEntity", "Caracterizacion")
                        .WithOne("RCsobremaduras")
                        .HasForeignKey("Backend.Models.RCsobremadurasEntity", "Tiempo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracterizacion");
                });

            modelBuilder.Entity("Backend.Models.RondasEntity", b =>
                {
                    b.HasOne("Backend.Models.CatacionEntity", "Catacion")
                        .WithMany("Rondas")
                        .HasForeignKey("IdCatacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catacion");
                });

            modelBuilder.Entity("Backend.Models.SuministraEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.BodegaEntity", "Bodega")
                        .WithMany()
                        .HasForeignKey("IdBodega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeBeanFlowAPI.Models.TrillaEntity", "Trilla")
                        .WithMany()
                        .HasForeignKey("IdTrilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Trilla");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.BodegaEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.AreaAcopioEntity", "AreaAcopio")
                        .WithMany()
                        .HasForeignKey("Nlote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaAcopio");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.GuardarCafeEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.BodegaEntity", "Bodega")
                        .WithMany("SecadosGuardados")
                        .HasForeignKey("IdBodega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeBeanFlowAPI.Models.SecadoEntity", "Secado")
                        .WithMany("BodegasGuardadas")
                        .HasForeignKey("IdSecado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.HumedadEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.SecadoEntity", "Secado")
                        .WithMany("Humedades")
                        .HasForeignKey("IdSecado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.NcamaEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.SecadoEntity", "Secado")
                        .WithMany("Ncamas")
                        .HasForeignKey("IdSecado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.PesoVerdeEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.TrillaEntity", "Trilla")
                        .WithOne("PesoVerde")
                        .HasForeignKey("CoffeeBeanFlowAPI.Models.PesoVerdeEntity", "IdPesoVerde")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilla");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.SecadoEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.AreaAcopioEntity", "AreaAcopio")
                        .WithMany()
                        .HasForeignKey("Nlote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaAcopio");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.TemperaturaSecadoEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.SecadoEntity", "Secado")
                        .WithMany("TemperaturasSecado")
                        .HasForeignKey("IdSecado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.TermoHigrometriaEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.SecadoEntity", "Secado")
                        .WithMany("TermoHigrometrias")
                        .HasForeignKey("IdSecado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.TrillaEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.AreaAcopioEntity", "AreaAcopio")
                        .WithMany()
                        .HasForeignKey("Nlote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaAcopio");
                });

            modelBuilder.Entity("Backend.Models.CaracterizacionEntity", b =>
                {
                    b.Navigation("RCinmaduras");

                    b.Navigation("RCmaduras");

                    b.Navigation("RCsobremaduras");
                });

            modelBuilder.Entity("Backend.Models.CatacionEntity", b =>
                {
                    b.Navigation("Rondas");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.BodegaEntity", b =>
                {
                    b.Navigation("SecadosGuardados");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.SecadoEntity", b =>
                {
                    b.Navigation("BodegasGuardadas");

                    b.Navigation("Humedades");

                    b.Navigation("Ncamas");

                    b.Navigation("TemperaturasSecado");

                    b.Navigation("TermoHigrometrias");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.TrillaEntity", b =>
                {
                    b.Navigation("PesoVerde");
                });
#pragma warning restore 612, 618
        }
    }
}
