// <auto-generated />
using CoffeeBeanFlowAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeBeanFlowAPI.Migrations
{
    [DbContext(typeof(CoffeeBeanFlowDbContext))]
    [Migration("20251214051111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.AreaAcopioEntity", b =>
                {
                    b.Property<string>("Nlote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nlote");

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric")
                        .HasColumnName("altura");

                    b.Property<bool?>("Anaerobico")
                        .HasColumnType("boolean")
                        .HasColumnName("anaerobico");

                    b.Property<decimal?>("Disponible")
                        .HasColumnType("numeric")
                        .HasColumnName("disponible");

                    b.Property<string>("Enproceso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("enproceso");

                    b.Property<bool?>("Lavado")
                        .HasColumnType("boolean")
                        .HasColumnName("lavado");

                    b.Property<bool?>("Miel")
                        .HasColumnType("boolean")
                        .HasColumnName("miel");

                    b.Property<bool?>("Natural")
                        .HasColumnType("boolean")
                        .HasColumnName("natural");

                    b.Property<string>("Nfinca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nfinca");

                    b.Property<string>("Nproductor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nproductor");

                    b.Property<int>("Nrecibo")
                        .HasColumnType("integer")
                        .HasColumnName("nrecibo");

                    b.Property<string>("Otro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("otro");

                    b.Property<decimal?>("PDensidad_Fruta")
                        .HasColumnType("numeric")
                        .HasColumnName("pdensidad_fruta");

                    b.Property<decimal?>("PDensidad_Pergamino_Humedo")
                        .HasColumnType("numeric")
                        .HasColumnName("pdensidad_pergamino_humedo");

                    b.Property<decimal?>("PF_DMecanicos")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_dmecanicos");

                    b.Property<decimal?>("PF_Pergamino_Pulpa")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_pergamino_pulpa");

                    b.Property<decimal?>("PF_Pulpa_Pergamino")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_pulpa_pergamino");

                    b.Property<decimal?>("PF_Segundas")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_segundas");

                    b.Property<decimal?>("Robjetivo")
                        .HasColumnType("numeric")
                        .HasColumnName("robjetivo");

                    b.Property<decimal?>("Rtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("rtotal");

                    b.Property<bool?>("Semilavado")
                        .HasColumnType("boolean")
                        .HasColumnName("semilavado");

                    b.Property<bool>("Vendido")
                        .HasColumnType("boolean")
                        .HasColumnName("vendido");

                    b.Property<string>("Zona")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zona");

                    b.HasKey("Nlote");

                    b.ToTable("area_acopio");
                });
#pragma warning restore 612, 618
        }
    }
}
