// <auto-generated />
using System;
using CoffeeBeanFlowAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeBeanFlowAPI.Migrations
{
    [DbContext(typeof(CoffeeBeanFlowDbContext))]
    [Migration("20251214060206_AddBodegaAndGuardarCafe")]
    partial class AddBodegaAndGuardarCafe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.AreaAcopioEntity", b =>
                {
                    b.Property<string>("Nlote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nlote");

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric")
                        .HasColumnName("altura");

                    b.Property<bool?>("Anaerobico")
                        .HasColumnType("boolean")
                        .HasColumnName("anaerobico");

                    b.Property<decimal?>("Disponible")
                        .HasColumnType("numeric")
                        .HasColumnName("disponible");

                    b.Property<string>("Enproceso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("enproceso");

                    b.Property<bool?>("Lavado")
                        .HasColumnType("boolean")
                        .HasColumnName("lavado");

                    b.Property<bool?>("Miel")
                        .HasColumnType("boolean")
                        .HasColumnName("miel");

                    b.Property<bool?>("Natural")
                        .HasColumnType("boolean")
                        .HasColumnName("natural");

                    b.Property<string>("Nfinca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nfinca");

                    b.Property<string>("Nproductor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nproductor");

                    b.Property<int>("Nrecibo")
                        .HasColumnType("integer")
                        .HasColumnName("nrecibo");

                    b.Property<string>("Otro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("otro");

                    b.Property<decimal?>("PDensidad_Fruta")
                        .HasColumnType("numeric")
                        .HasColumnName("pdensidad_fruta");

                    b.Property<decimal?>("PDensidad_Pergamino_Humedo")
                        .HasColumnType("numeric")
                        .HasColumnName("pdensidad_pergamino_humedo");

                    b.Property<decimal?>("PF_DMecanicos")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_dmecanicos");

                    b.Property<decimal?>("PF_Pergamino_Pulpa")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_pergamino_pulpa");

                    b.Property<decimal?>("PF_Pulpa_Pergamino")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_pulpa_pergamino");

                    b.Property<decimal?>("PF_Segundas")
                        .HasColumnType("numeric")
                        .HasColumnName("pf_segundas");

                    b.Property<decimal?>("Robjetivo")
                        .HasColumnType("numeric")
                        .HasColumnName("robjetivo");

                    b.Property<decimal?>("Rtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("rtotal");

                    b.Property<bool?>("Semilavado")
                        .HasColumnType("boolean")
                        .HasColumnName("semilavado");

                    b.Property<bool>("Vendido")
                        .HasColumnType("boolean")
                        .HasColumnName("vendido");

                    b.Property<string>("Zona")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zona");

                    b.HasKey("Nlote");

                    b.ToTable("area_acopio");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.BodegaEntity", b =>
                {
                    b.Property<int>("IdBodega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_bodega");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBodega"));

                    b.Property<int?>("CantidadSacos")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_sacos");

                    b.Property<decimal?>("DBellota")
                        .HasColumnType("numeric")
                        .HasColumnName("d_bellota");

                    b.Property<decimal?>("DPergamino")
                        .HasColumnType("numeric")
                        .HasColumnName("d_pergamino");

                    b.Property<DateTime?>("FinicioReposo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finicio_reposo");

                    b.Property<decimal?>("Hfinal")
                        .HasColumnType("numeric")
                        .HasColumnName("hfinal");

                    b.Property<decimal?>("Hinicial")
                        .HasColumnType("numeric")
                        .HasColumnName("hinicial");

                    b.Property<string>("Nlote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nlote");

                    b.Property<decimal?>("PMHRelativa")
                        .HasColumnType("numeric")
                        .HasColumnName("pmh_relativa");

                    b.Property<decimal?>("PMTExterna")
                        .HasColumnType("numeric")
                        .HasColumnName("pmt_externa");

                    b.Property<decimal?>("PMTInterna")
                        .HasColumnType("numeric")
                        .HasColumnName("pmt_interna");

                    b.Property<decimal?>("WBellota")
                        .HasColumnType("numeric")
                        .HasColumnName("w_bellota");

                    b.Property<decimal?>("WPergamino")
                        .HasColumnType("numeric")
                        .HasColumnName("w_pergamino");

                    b.HasKey("IdBodega");

                    b.HasIndex("Nlote");

                    b.ToTable("bodega");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.GuardarCafeEntity", b =>
                {
                    b.Property<int>("IdSecado")
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    b.Property<int>("IdBodega")
                        .HasColumnType("integer")
                        .HasColumnName("id_bodega");

                    b.Property<int>("CantidadSacos")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_sacos");

                    b.HasKey("IdSecado", "IdBodega");

                    b.HasIndex("IdBodega");

                    b.ToTable("guardar_cafe");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.HumedadEntity", b =>
                {
                    b.Property<int>("IdHumedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_humedad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHumedad"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Humedad")
                        .HasColumnType("numeric")
                        .HasColumnName("humedad");

                    b.Property<int>("IdSecado")
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    b.HasKey("IdHumedad");

                    b.HasIndex("IdSecado");

                    b.ToTable("humedad");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.NcamaEntity", b =>
                {
                    b.Property<int>("IdNcama")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ncama");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNcama"));

                    b.Property<int>("IdSecado")
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    b.Property<string>("NumeroCama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_cama");

                    b.HasKey("IdNcama");

                    b.HasIndex("IdSecado");

                    b.ToTable("ncama");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.SecadoEntity", b =>
                {
                    b.Property<int>("IdSecado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSecado"));

                    b.Property<int?>("Dsecado")
                        .HasColumnType("integer")
                        .HasColumnName("dsecado");

                    b.Property<DateTime?>("Ffinal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ffinal");

                    b.Property<DateTime>("Finicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finicio");

                    b.Property<string>("Nlote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nlote");

                    b.HasKey("IdSecado");

                    b.HasIndex("Nlote");

                    b.ToTable("secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.TemperaturaSecadoEntity", b =>
                {
                    b.Property<int>("IdTemperaturaSecado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_temperatura_secado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTemperaturaSecado"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdSecado")
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("numeric")
                        .HasColumnName("temperatura");

                    b.HasKey("IdTemperaturaSecado");

                    b.HasIndex("IdSecado");

                    b.ToTable("temperatura_secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.TermoHigrometriaEntity", b =>
                {
                    b.Property<int>("IdTermoHigrometria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_termo_higrometria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTermoHigrometria"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("HumedadAmbiente")
                        .HasColumnType("numeric")
                        .HasColumnName("humedad_ambiente");

                    b.Property<int>("IdSecado")
                        .HasColumnType("integer")
                        .HasColumnName("id_secado");

                    b.Property<decimal>("TemperaturaAmbiente")
                        .HasColumnType("numeric")
                        .HasColumnName("temperatura_ambiente");

                    b.HasKey("IdTermoHigrometria");

                    b.HasIndex("IdSecado");

                    b.ToTable("termo_higrometria");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.BodegaEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.AreaAcopioEntity", "AreaAcopio")
                        .WithMany()
                        .HasForeignKey("Nlote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaAcopio");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.GuardarCafeEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.BodegaEntity", "Bodega")
                        .WithMany("SecadosGuardados")
                        .HasForeignKey("IdBodega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeBeanFlowAPI.Models.SecadoEntity", "Secado")
                        .WithMany("BodegasGuardadas")
                        .HasForeignKey("IdSecado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.HumedadEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.SecadoEntity", "Secado")
                        .WithMany("Humedades")
                        .HasForeignKey("IdSecado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.NcamaEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.SecadoEntity", "Secado")
                        .WithMany("Ncamas")
                        .HasForeignKey("IdSecado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.SecadoEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.AreaAcopioEntity", "AreaAcopio")
                        .WithMany()
                        .HasForeignKey("Nlote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaAcopio");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.TemperaturaSecadoEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.SecadoEntity", "Secado")
                        .WithMany("TemperaturasSecado")
                        .HasForeignKey("IdSecado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.TermoHigrometriaEntity", b =>
                {
                    b.HasOne("CoffeeBeanFlowAPI.Models.SecadoEntity", "Secado")
                        .WithMany("TermoHigrometrias")
                        .HasForeignKey("IdSecado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secado");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.BodegaEntity", b =>
                {
                    b.Navigation("SecadosGuardados");
                });

            modelBuilder.Entity("CoffeeBeanFlowAPI.Models.SecadoEntity", b =>
                {
                    b.Navigation("BodegasGuardadas");

                    b.Navigation("Humedades");

                    b.Navigation("Ncamas");

                    b.Navigation("TemperaturasSecado");

                    b.Navigation("TermoHigrometrias");
                });
#pragma warning restore 612, 618
        }
    }
}
