// <auto-generated />
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.Humedad
{
    [DbContext(typeof(HumedadContext))]
    [Migration("20250818011540_InitialCreate_Humedad")]
    partial class InitialCreate_Humedad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.HumedadItem", b =>
                {
                    b.Property<int>("ID_Humedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Humedad"));

                    b.Property<int>("ID_Secado")
                        .HasColumnType("integer");

                    b.Property<decimal>("PHumedad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Temperatura")
                        .HasColumnType("integer");

                    b.HasKey("ID_Humedad");

                    b.ToTable("Humedad");
                });
#pragma warning restore 612, 618
        }
    }
}
