// <auto-generated />
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.TemperaturaSecado
{
    [DbContext(typeof(TemperaturaSecadoContext))]
    [Migration("20250617173516_InitialCreate_TemperaturaSecadoContext")]
    partial class InitialCreate_TemperaturaSecadoContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.TemperaturaSecadoItem", b =>
                {
                    b.Property<int>("ID_Temperatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Temperatura"));

                    b.Property<int>("ID_Secado")
                        .HasColumnType("integer");

                    b.Property<int>("Lectura")
                        .HasColumnType("integer");

                    b.HasKey("ID_Temperatura");

                    b.ToTable("TemperaturaSecado");
                });
#pragma warning restore 612, 618
        }
    }
}
