// <auto-generated />
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.PesoVerde
{
    [DbContext(typeof(PesoVerdeContext))]
    [Migration("20250617173222_InitialCreate_PesoVerdeContext")]
    partial class InitialCreate_PesoVerdeContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.PesoVerdeItem", b =>
                {
                    b.Property<int>("ID_PesoVerde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_PesoVerde"));

                    b.Property<int>("ID_PesoTrilla")
                        .HasColumnType("integer");

                    b.Property<decimal>("WFinferior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Wfinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Winferiores")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_PesoVerde");

                    b.ToTable("PesoVerde");
                });
#pragma warning restore 612, 618
        }
    }
}
