// <auto-generated />
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.Rondas
{
    [DbContext(typeof(RondasContext))]
    [Migration("20250818011632_InitialCreate_Rondas")]
    partial class InitialCreate_Rondas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.RondasItem", b =>
                {
                    b.Property<int>("ID_Rondas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Rondas"));

                    b.Property<int>("ID_catacion")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor_calidad")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Rondas");

                    b.ToTable("Rondas");
                });
#pragma warning restore 612, 618
        }
    }
}
