// <auto-generated />
using System;
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.Formulario_Caracterizacion
{
    [DbContext(typeof(Formulario_CaracterizacionContext))]
    [Migration("20250617172957_InitialCreate_Formulario_CaracterizacionContext")]
    partial class InitialCreate_Formulario_CaracterizacionContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.Formulario_CaracterizacionItem", b =>
                {
                    b.Property<DateTime>("Tiempo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Broca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Cinmaduras")
                        .HasColumnType("integer");

                    b.Property<int>("Cobjetivo")
                        .HasColumnType("integer");

                    b.Property<int>("Csecas")
                        .HasColumnType("integer");

                    b.Property<int>("Csobremaduras")
                        .HasColumnType("integer");

                    b.Property<int>("Cverdes")
                        .HasColumnType("integer");

                    b.Property<decimal>("DRmaduras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Densidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Emaduracion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mtabla")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nlote_AreaAcopio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PCdebajo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PCencima")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PCobjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PCsecas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PCverdes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Secos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Vanos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Tiempo");

                    b.ToTable("Formulario_Caracterizacion");
                });
#pragma warning restore 612, 618
        }
    }
}
