// <auto-generated />
using System;
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.Trilla
{
    [DbContext(typeof(TrillaContext))]
    partial class TrillaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.TrillaItem", b =>
                {
                    b.Property<int>("ID_Trilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Trilla"));

                    b.Property<DateTime>("FFinalReposo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nlote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("POinferiores")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pbarreduras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pcaracolillo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pcataduras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pescogeduras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pinferiores")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pmadres")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pmenudos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pprimera")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Psegundas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RTeoricoPelado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RTeoricoSeleccion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RfinalPelado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RfinalSeleccion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WVerdeFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WVerdeTeorico")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Trilla");

                    b.ToTable("Trilla");
                });
#pragma warning restore 612, 618
        }
    }
}
