// <auto-generated />
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.Suministra
{
    [DbContext(typeof(SuministraContext))]
    [Migration("20250818011648_InitialCreate_Suministra")]
    partial class InitialCreate_Suministra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.SuministraItem", b =>
                {
                    b.Property<int>("ID_Bodega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Bodega"));

                    b.Property<int>("ID_Trilla")
                        .HasColumnType("integer");

                    b.HasKey("ID_Bodega");

                    b.ToTable("Suministra");
                });
#pragma warning restore 612, 618
        }
    }
}
