// <auto-generated />
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.TermoHigrometria
{
    [DbContext(typeof(TermoHigrometriaContext))]
    partial class TermoHigrometriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.TermoHigrometriaItem", b =>
                {
                    b.Property<int>("ID_Termo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Termo"));

                    b.Property<decimal>("Hrelativa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ID_Secado")
                        .HasColumnType("integer");

                    b.Property<int>("Texterna")
                        .HasColumnType("integer");

                    b.Property<int>("Tinterna")
                        .HasColumnType("integer");

                    b.HasKey("ID_Termo");

                    b.ToTable("TermoHigrometria");
                });
#pragma warning restore 612, 618
        }
    }
}
