// <auto-generated />
using System;
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations.RCsobremaduras
{
    [DbContext(typeof(RCsobremadurasContext))]
    partial class RCsobremadurasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.RCsobremadurasItem", b =>
                {
                    b.Property<int>("ID_sobremaduras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_sobremaduras"));

                    b.Property<decimal>("Gbx")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Promedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Tiempo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID_sobremaduras");

                    b.ToTable("RCsobremaduras");
                });
#pragma warning restore 612, 618
        }
    }
}
