// <auto-generated />
using CoffeBeanFlowDB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeBeanFlowDB.Migrations
{
    [DbContext(typeof(Area_AcopioContext))]
    [Migration("20250818011435_InitialCreate_AreaAcopio")]
    partial class InitialCreate_AreaAcopio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeBeanFlowDB.Models.Area_AcopioItem", b =>
                {
                    b.Property<string>("Nlote")
                        .HasColumnType("text");

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DFruta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Despulpado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Disponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Dpergamino_humedo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Enproceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ID_Secado")
                        .HasColumnType("integer");

                    b.Property<string>("Nfinca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nproductor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Nrecibo")
                        .HasColumnType("integer");

                    b.Property<decimal>("PDmecanicos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PPergaminoPulpa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PPulpaPergamino")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Psegundas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Robjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rsobreobjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Vendido")
                        .HasColumnType("boolean");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Nlote");

                    b.ToTable("Area_Acopio");
                });
#pragma warning restore 612, 618
        }
    }
}
